//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLMuseum.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Painting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Painting()
        {
            this.Schedule = new HashSet<Schedule>();
        }
    
        public int ID_Painting { get; set; }
        public string Name { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<double> Price_rub { get; set; }
        public Nullable<int> ID_Hall { get; set; }
        public Nullable<int> ID_Author { get; set; }
        public Nullable<int> ID_Execution { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Execution Execution { get; set; }
        public virtual Hall Hall { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedule { get; set; }
    }
}
