//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLMuseum.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int ID_Painting { get; set; }
        public int ID_Exhibition { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
    
        public virtual Exhibition Exhibition { get; set; }
        public virtual Painting Painting { get; set; }
    }
}
